# 分析 MIDI 文件

In [1]:
import os
from data import __PATH__
from data.preprocess import analyse_all_midi

midi_file_path = os.path.join(__PATH__, 'classical')
processed_midi_dataset = [x for x in analyse_all_midi(midi_file_path)]
processed_midi_dataset[:10]

[('C:\\Users\\ROG\\Desktop\\large_project\\DeepMidi\\data\\classical\\mz_333_2.mid',
  [('Eb_3', 2.0),
   ('Eb_3', 1.0),
   ('F_3', 1.0),
   ('G_3', 1.0),
   ('E_4', 1.0),
   ('F_4', 0.5),
   ('C_5', 0.5),
   ('Bb_4', 0.25),
   ('G#_4', 0.25),
   ('G_4', 0.25),
   ('F_4', 0.25),
   ('A_2', 0.25),
   ('Bb_2', 0.25),
   ('C_3', 0.25),
   ('Bb_2', 0.25),
   ('Bb_2', 1.0),
   ('G#_4', 0.25),
   ('G_4', 0.25),
   ('F_4', 0.25),
   ('Eb_4', 0.25),
   ('G_5', 0.25),
   ('D_5', 0.25),
   ('Eb_5', 0.25),
   ('C_5', 0.25),
   ('Bb_4', 1.0),
   ('G_4', 0.25),
   ('Eb_5', 0.25),
   ('D_5', 0.25),
   ('C#_5', 0.25),
   ('F_4', 0.25),
   ('Eb_4', 1.5),
   ('Bb_2', 2.0),
   ('G_3', 1.0),
   ('G#_3', 1.0),
   ('F_4', 0.25),
   ('Eb_4', 1.0),
   ('Eb_3', 0.25),
   ('G_3', 0.25),
   ('Bb_3', 0.25),
   ('G_3', 0.25),
   ('Eb_3', 0.25),
   ('G_3', 0.25),
   ('Bb_3', 0.25),
   ('G_3', 0.25),
   ('Eb_3', 0.25),
   ('G_3', 0.25),
   ('Bb_3', 0.25),
   ('G_3', 0.25),
   ('G#_4', 1.5),
   ('Eb_5', 0.5),
   ('E

# MIDI 向量化编码

In [2]:
from data.note_digitize import encode as d_encode
from data.note_vectorize import encode as v_encode

dataset = []
for _ in processed_midi_dataset:
    dataset.append((_[0], [x[0] for x in _[1] if '_' in x[0] and x[0][-1].isdigit()]))
dataset = [(_[0], [v_encode(d_encode(x)) for x in _[1]]) for _ in dataset]
dataset[0][1][:10]

[tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        dtype=torch.int8),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        dtype=torch.int8),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

# 数据处理，处理为自回归格式

In [3]:
from data.auto_regression_preprocess import auto_regression_preprocess

n_gram = 5
auto_regression_dataset = [(_[0], auto_regression_preprocess(_[1], n_gram)) for _ in dataset]
auto_regression_dataset[0][1][0], auto_regression_dataset[0][1][1]

(tensor([[[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]],
 
         [[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]],
 
         [[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]],
 
         ...,
 
         [[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]],
 
         [[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]],
 
         [[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]]], dtype=torch.int8),
 tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0

# 数据集参数设置

In [114]:
import torch

BATCH_SIZE = 80
DEVICE = torch.device('cuda')
DTYPE = torch.float32
DATA_SLICE = 8192

# 创建数据集加载器

In [115]:
import torch
from data.auto_regression_preprocess import get_auto_regression_dataset_loaders

auto_regression_dataset_inputs = auto_regression_dataset[0][1][0].tolist()
auto_regression_dataset_labels = auto_regression_dataset[0][1][1].tolist()
for _ in auto_regression_dataset[1:]:
    auto_regression_dataset_inputs.extend(_[1][0].tolist())
    auto_regression_dataset_labels.extend(_[1][1].tolist())

auto_regression_dataset_inputs = torch.tensor(auto_regression_dataset_inputs[:DATA_SLICE], dtype=DTYPE, device=DEVICE)
auto_regression_dataset_labels = torch.tensor(auto_regression_dataset_labels[:DATA_SLICE], dtype=DTYPE, device=DEVICE)
print(auto_regression_dataset_inputs, auto_regression_dataset_labels)
print(auto_regression_dataset_inputs.shape, auto_regression_dataset_labels.shape)
auto_regression_dataset_train_loader, auto_regression_dataset_valid_loader = get_auto_regression_dataset_loaders(auto_regression_dataset_inputs, auto_regression_dataset_labels, train_ratio=0.90, batch_size=BATCH_SIZE)

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0

# 初始化自回归模型

In [128]:
from deeplotx import AutoRegression

feature_dim = auto_regression_dataset[0][1][1][0].shape[-1]
model = AutoRegression(feature_dim=feature_dim, hidden_dim=512, recursive_layers=8, dtype=DTYPE)
model, model.dtype, model.device

(AutoRegression(
   (lstm): LSTM(120, 512, num_layers=8, batch_first=True, bidirectional=True)
   (regressive_head): LinearRegression(
     (fc1): Linear(in_features=1024, out_features=1024, bias=True)
     (fc1_to_fc4_res): Linear(in_features=1024, out_features=64, bias=True)
     (fc2): Linear(in_features=1024, out_features=768, bias=True)
     (fc3): Linear(in_features=768, out_features=128, bias=True)
     (fc4): Linear(in_features=128, out_features=64, bias=True)
     (fc5): Linear(in_features=64, out_features=120, bias=True)
     (parametric_relu_1): PReLU(num_parameters=1)
     (parametric_relu_2): PReLU(num_parameters=1)
     (parametric_relu_3): PReLU(num_parameters=1)
     (parametric_relu_4): PReLU(num_parameters=1)
   )
 ),
 torch.float32,
 device(type='cuda'))

# 模型训练

In [129]:
from torch.utils.tensorboard import SummaryWriter
from datetime import datetime
import torch
from torch import nn, optim

num_epochs = 100_000_000
elastic_net_param = {'alpha': 1e-4, 'rho': 0.2}
learning_rate = 2e-6
train_loss_threshold = 0.
valid_loss_threshold = 0.
criterion = nn.CrossEntropyLoss()
optim = optim.Adamax(model.parameters(), lr=learning_rate)

log_dir = os.path.join("runs", datetime.now().strftime("%Y%m%d-%H%M%S"))
writer = SummaryWriter(log_dir)

for name, param in model.named_parameters():
    writer.add_histogram(f'parameters/{name}', param, 0)

for epoch in range(num_epochs):
    model.train()
    total_loss = 0.0
    for batch_inputs, batch_labels in auto_regression_dataset_train_loader:
        outputs = torch.softmax(model.forward(batch_inputs, model.initial_state(batch_size=batch_inputs.shape[0]))[0], dim=-1)
        loss = criterion(outputs, batch_labels) + model.elastic_net(alpha=elastic_net_param['alpha'], rho=elastic_net_param['rho'])
        optim.zero_grad()
        loss.backward()
        optim.step()
        total_loss += loss.item()
    if epoch % 3 == 0:
        total_valid_loss = 0.0
        for batch_inputs, batch_labels in auto_regression_dataset_valid_loader:
            with torch.no_grad():
                model.eval()
                outputs = torch.softmax(model.forward(batch_inputs, model.initial_state(batch_size=batch_inputs.shape[0]))[0], dim=-1)
                loss = criterion(outputs, batch_labels) + model.elastic_net(alpha=elastic_net_param['alpha'], rho=elastic_net_param['rho'])
                total_valid_loss += loss.item()
                model.train()
        print(f"Epoch {epoch + 1}/{num_epochs} | "
              f"Train Loss: {total_loss:.4f} | "
              f"Valid Loss: {total_valid_loss:.4f}")
        writer.add_scalar('loss/valid', total_valid_loss, epoch)
        
        for name, param in model.named_parameters():
            writer.add_histogram(f'parameters/{name}', param, epoch)
            
        if total_valid_loss <= valid_loss_threshold:
            break
    print(f"Epoch {epoch + 1}/{num_epochs} | Train Loss: {total_loss:.4f}")
    writer.add_scalar('loss/train', total_loss, epoch)
    if total_loss <= train_loss_threshold:
        break

Epoch 1/100000000 | Train Loss: 2531.2107 | Valid Loss: 298.3081
Epoch 1/100000000 | Train Loss: 2531.2107
Epoch 2/100000000 | Train Loss: 2513.1891
Epoch 3/100000000 | Train Loss: 2495.2586
Epoch 4/100000000 | Train Loss: 2477.4109 | Valid Loss: 291.9608
Epoch 4/100000000 | Train Loss: 2477.4109
Epoch 5/100000000 | Train Loss: 2459.6494
Epoch 6/100000000 | Train Loss: 2441.9693
Epoch 7/100000000 | Train Loss: 2424.3716 | Valid Loss: 285.7022
Epoch 7/100000000 | Train Loss: 2424.3716
Epoch 8/100000000 | Train Loss: 2406.8614
Epoch 9/100000000 | Train Loss: 2389.4338
Epoch 10/100000000 | Train Loss: 2372.0864 | Valid Loss: 279.5343
Epoch 10/100000000 | Train Loss: 2372.0864
Epoch 11/100000000 | Train Loss: 2354.8218
Epoch 12/100000000 | Train Loss: 2337.6440
Epoch 13/100000000 | Train Loss: 2320.5509 | Valid Loss: 273.4555
Epoch 13/100000000 | Train Loss: 2320.5509
Epoch 14/100000000 | Train Loss: 2303.5424
Epoch 15/100000000 | Train Loss: 2286.6102
Epoch 16/100000000 | Train Loss: 2269


KeyboardInterrupt



# 模型测试

In [149]:
import random
from data.note_digitize import decode as d_decode
from data.note_vectorize import decode as v_decode

model.eval()
for batch_inputs, batch_labels in auto_regression_dataset_valid_loader:
    with torch.no_grad():
        print('Input: ')
        for b in batch_inputs:
            print([d_decode(v_decode(x)) for x in b])
        outputs = torch.softmax(model.forward(batch_inputs, model.initial_state(batch_size=batch_inputs.shape[0]))[0], dim=-1)
        print(outputs)
        outputs = torch.multinomial(outputs, num_samples=3)
        print('Predict: ')
        print([d_decode(random.sample(x, 1)[0]) for x in outputs.tolist()])
        print('-' * 36)
        print('Label: ')
        for b in batch_labels:
            print(d_decode(v_decode(b)))
    break

Input: 
['E_4', 'G_3', 'G_4', 'A#_3']
['C_5', 'A#_4', 'A#_3', 'F_4']
['A#_3', 'G_5', 'A_5', 'F_3']
['G_3', 'C_4', 'C_5', 'F_3']
['G#_5', 'A#_3', 'A_5', 'D_3']
['A#_3', 'F_5', 'D#_4', 'G_5']
['F_4', 'D_4', 'F_4', 'D_5']
['A#_5', 'A#_3', 'F_5', 'D_3']
['F_3', 'E_5', 'F_5', 'G_5']
['C#_5', 'A#_3', 'F_4', 'C_5']
['D_5', 'C_5', 'F_5', 'D#_5']
['A_3', 'A_3', 'A_3', 'A_3']
['D#_5', 'F_4', 'E_5', 'G#_3']
['E_4', 'G_3', 'A_4', 'A_5']
['A_3', 'F_5', 'F_5', 'D_3']
['C_4', 'C_5', 'F_5', 'C_5']
['C_5', 'D_5', 'D_4', 'D#_5']
['A_3', 'A_3', 'A_3', 'E_3']
['F_5', 'D#_3', 'D#_5', 'C_4']
['F_4', 'C_4', 'F_4', 'D#_4']
['C_4', 'C_5', 'F_3', 'A_3']
['A_3', 'C_4', 'C_4', 'C_4']
['A#_3', 'F_3', 'A#_5', 'A#_3']
['G_3', 'A#_3', 'C_3', 'C_6']
['G_5', 'F_5', 'D#_3', 'D#_5']
['D#_5', 'D_5', 'C_5', 'A#_4']
['G#_3', 'A#_4', 'C_5', 'F_3']
['A_3', 'F_5', 'F_5', 'F_5']
['A_3', 'A_3', 'A_3', 'A_3']
['C_6', 'A#_5', 'A_5', 'G_5']
['E_3', 'E_3', 'A_3', 'A_3']
['A_5', 'A#_3', 'A_5', 'D_3']
['A_3', 'F_5', 'D#_5', 'D_3']
['F

In [150]:
model._model_name = 'DATA8192-EPOCH321'
model.save()

AutoRegression(
  (lstm): LSTM(120, 512, num_layers=8, batch_first=True, bidirectional=True)
  (regressive_head): LinearRegression(
    (fc1): Linear(in_features=1024, out_features=1024, bias=True)
    (fc1_to_fc4_res): Linear(in_features=1024, out_features=64, bias=True)
    (fc2): Linear(in_features=1024, out_features=768, bias=True)
    (fc3): Linear(in_features=768, out_features=128, bias=True)
    (fc4): Linear(in_features=128, out_features=64, bias=True)
    (fc5): Linear(in_features=64, out_features=120, bias=True)
    (parametric_relu_1): PReLU(num_parameters=1)
    (parametric_relu_2): PReLU(num_parameters=1)
    (parametric_relu_3): PReLU(num_parameters=1)
    (parametric_relu_4): PReLU(num_parameters=1)
  )
)